import React from 'react'
import Head from 'next/head'

function Heading(){
	return (
			<Head className="bg-blue-500 h-32 border-2">
	        	<title>Create Next App</title>
	        	<meta name="description" content="Generated by create next app" />
	        	<link rel="icon" href="/favicon.ico" />
	      	</Head>
		)
}

export default Heading